import jsPDF from "jspdf";

/**
 * Generates a professional formatted PDF report for PharmFlow
 * @param {Object} reportData - The consolidated report data
 */
export const generateReportPDF = (reportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header & Branding
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("PharmFlow Intelligence", 20, 25);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text("Professional Pharmacy Management Protocol v2.0", 20, 32);
    
    // Metadata
    doc.setTextColor(100, 116, 139); // slate-500
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Report Generation Timestamp: ${new Date().toLocaleString()}`, 20, 50);
    doc.text(`Analysis Range: ${reportData.summary.range}`, 20, 55);
    
    // Summary Section
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(20, 65, pageWidth - 20, 65);
    
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY", 20, 75);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    
    // Summary Grid-like display
    doc.text("Metric", 20, 85);
    doc.text("Value", 100, 85);
    doc.line(20, 87, 140, 87);
    
    doc.text("Operating Revenue (Today)", 20, 95);
    doc.text(`INR ${reportData.summary.revenue.toLocaleString()}`, 100, 95);
    
    doc.text("Monthly Revenue Cycle", 20, 103);
    doc.text(`INR ${reportData.summary.monthlyRevenue.toLocaleString()}`, 100, 103);
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129); // emerald-500
    doc.text("Net Profit Protocol", 20, 111);
    doc.text(`INR ${reportData.summary.profit.toLocaleString()}`, 100, 111);
    
    // Sales Trend Section
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("SALES VELOCITY TREND", 20, 125);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105); // slate-600
    
    let y = 135;
    doc.setFont("helvetica", "bold");
    doc.text("Date", 25, y);
    doc.text("Revenue Distribution", 100, y);
    doc.line(20, y + 2, 140, y + 2);
    y += 10;
    
    doc.setFont("helvetica", "normal");
    reportData.salesTrend.forEach((item, index) => {
        if (y > 250) {
            doc.addPage();
            y = 20;
        }
        doc.text(item.date, 25, y);
        doc.text(`INR ${item.revenue.toLocaleString()}`, 100, y);
        y += 8;
    });

    // Low Stock Alerts
    y += 10;
    if (y > 250) {
        doc.addPage();
        y = 20;
    }
    
    doc.setTextColor(225, 29, 72); // rose-600
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("CRITICAL STOCK ALERTS", 20, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    
    if (reportData.lowStock.length === 0) {
        doc.text("System Status: All stocks within optimal parameters.", 25, y);
        y += 10;
    } else {
        reportData.lowStock.forEach(item => {
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
            doc.text(`${item.name} (Qty: ${item.qty} / Limit: ${item.threshold})`, 25, y);
            y += 7;
        });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(
            `CONFIDENTIAL - PHARMFLOW INTELLIGENCE EXPORT | Page ${i} of ${pageCount}`,
            pageWidth / 2,
            285,
            { align: "center" }
        );
        doc.text("Generated by PharmFlow Pro Architecture", pageWidth / 2, 290, { align: "center" });
    }

    doc.save(`PharmFlow_Intelligence_Report_${Date.now()}.pdf`);
};
